### ISSUE TITLE
Can't initialize the db - ImportError for exceptions module

### ISSUE THREAD

**Issue by giladbeeri** [belwase/fullstack_flask_exercise#2]
See below:

```
(ashish) ~/p/fullstack_flask_exercise (master)> set FLASK_APP main.py
(ashish) ~/p/fullstack_flask_exercise (master)> echo $FLASK_APP
main.py
(ashish) ~/p/fullstack_flask_exercise (master)> flask db init
Usage: flask db init [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/gilad/venvs/ashish/local/lib/python2.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/gilad/projects/fullstack_flask_exercise/app/__init__.py", line 11, in <module>
    from app import routes, models
  File "/home/gilad/projects/fullstack_flask_exercise/app/routes.py", line 4, in <module>
    from app.controllers import EmployeeView
  File "/home/gilad/projects/fullstack_flask_exercise/app/controllers.py", line 1, in <module>
    from app.base import APIEndpoint, BadRequest
  File "/home/gilad/projects/fullstack_flask_exercise/app/base.py", line 3, in <module>
    from .exceptions import BadRequest
ImportError: No module named exceptions

````

**Comment by belwase** [comment]
my mistake. just commited exceptions.py
